telegram_redis_db: 1
train_redis_db: 4
captain_redis_db: 5
telegram_log_path: 'log/telegram_bot.log'
captain_log_path: 'log/captain.log'

stop_trade_limit:
  per_order: 0.05
  avg_last_5: 0.01

max_order_usd: 2
maxx_thresh_koef: 0.97
minn_thresh_koef: 0.98
